[package]
name = "rsnaker"
version = "0.1.2"
edition = "2024"
authors = ["RF"]
description = "A good old retro Snake in terminal UI"
license = "GPL-3.0-only"
documentation = "https://docs.rs/rsnaker"
repository = "https://github.com/FromTheRags/rsnake"
readme = "README.md"
keywords = ["Ratatui", "TUI", "Snake", "Game", "retro"]
categories = ["command-line-utilities"]
rust-version = "1.85.0"

[dependencies]
#Use for terminal rendering
crossterm = { version = "0.29", features = ["events"] }
#TUI
#see https://docs.rs/ratatui/latest/ratatui/widgets/trait.WidgetRef.html need to have better performance avoiding cloning widget each time
#https://github.com/ratatui/ratatui/discussions/1274
ratatui = { version = "0.30.0-alpha.5", features = ["unstable-widget-ref"] }
#Use for random fruits position
rand = "0.9"
#Use for Cli parsing
clap = { version = "4.5", features = ["derive"] }
#Use for serialisation/deserialisation of game parameters
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
toml_edit = "0.23.4"
#Use in macro for clap, to check input is one grapheme-long (One character)
unicode-segmentation = "1.12.0"


#For testing cli easily
[dev-dependencies]
assert_cmd = { version = "2.0.17" }
predicates = "3.1.3"

[[bin]]
name = "rsnake"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[profile.release]
strip = "symbols"  # since Rust 1.73+
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
#For Performance flamegraph using https://github.com/mstange/samply (more user/window friendly, than flamegraph-rs)
#Build with: cargo build --profile profiling
#Run with:samply record ./target/profiling/yourrustprogram
#NB allow connection to 127.0.0.1 in firefox, like disabling Ublock for this page