use clap::ValueEnum;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;
use time::macros::format_description;
use tracing_subscriber::fmt::time::LocalTime;
use tracing_subscriber::prelude::*;
use tracing_subscriber::{fmt, reload, EnvFilter, Registry};

#[derive(Debug, Copy, Clone, Serialize, Deserialize, ValueEnum, Default, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum LogLevel {
    #[default]
    Off,
    Error,
    Warn,
    Info,
    Debug,
    Trace,
}
/*
[ App ]
│
▼ (by update_log_level)
[ RELOAD_HANDLE ] ───(modify function)───► [ EnvFilter (e.g.: "info") ]
│
▼ (apply the filter)
[ Log file ]
Work thanks to modify function: pub fn modify(&self, f: impl FnOnce(&mut L)) -> Result<(), Error>
Invokes a closure with a mutable reference to the current layer or filter, allowing it to be modified in place.
So the RELOAD_HANDLE itself is only written once, that the EnvFilter, which is updated as a &mut param
*/
static RELOAD_HANDLE: OnceLock<reload::Handle<EnvFilter, Registry>> = OnceLock::new();

/// Initializes the global logger.
/// Writing a Lib? Only use the tracing crate and its macros (info!, span!). Do not initialize anything.
/// Writing a Binary? Use tracing-subscriber to build the registry and handlers.
/// Missing dependency logs? Check your `EnvFilter` string rules and ensure the "log" feature is enabled on tracing-subscriber to catch legacy logs
/// Returns a `WorkerGuard` that must be kept alive to ensure logs are flushed to the file.
/// If later wanna do rsyslog (libc): <https://docs.rs/syslog-tracing/0.3.1/syslog_tracing/struct.Syslog.html>
/// Or the newcomer full rust: <https://crates.io/crates/tracing-rfc-5424>
pub fn init_logger(
    level: LogLevel,
    file_name: &str,
) -> Option<tracing_appender::non_blocking::WorkerGuard> {
    let file_appender = tracing_appender::rolling::never(".", file_name);
    let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);
    //To only keep my logs, as sled logs are useless (and otherwise collected),
    // Each dependency log level can be configured with the EnvFilter, e.g.: "sled=info,rsnaker=debug"
    let filter = EnvFilter::new(format!("rsnaker={},sled=off", log_level_to_str(level)));
    let (filter_layer, reload_handle) = reload::Layer::new(filter);
    //as default is:2026-05-16T12:49:06.919872Z, and we want to have [hour]:[minute]:[second][sub]
    //LocalTime instead of UTC, to have the local time
    let time_format = LocalTime::new(format_description!(
        "[hour]:[minute]:[second].[subsecond digits:6]"
    ));

    let subscriber = tracing_subscriber::registry().with(filter_layer).with(
        fmt::layer()
            .with_writer(non_blocking)
            .with_timer(time_format) // shorter time
            .with_ansi(false) // Disable ANSI colors in the logfile
            .with_target(false) //we do not want the name of the module as we have set the file and line number already
            .with_thread_names(true) //or .with_thread_ids(), but name more useful
            .with_line_number(true) // Added line numbers
            .with_file(true), // Also added the filename for more context
    );

    if subscriber.try_init().is_err() {
        eprintln!("Failed to initialize logger: logger already initialized");
    } else {
        let _ = RELOAD_HANDLE.set(reload_handle);
    }

    Some(guard)
}

/// Updates the global log level dynamically.
pub fn update_log_level(level: LogLevel) {
    if let Some(handle) = RELOAD_HANDLE.get() {
        let _ = handle.modify(|filter| {
            if let Ok(new_filter) =
                EnvFilter::try_new(format!("rsnaker={},sled=off", log_level_to_str(level)))
            {
                *filter = new_filter;
            }
        });
    }
}

fn log_level_to_str(level: LogLevel) -> &'static str {
    //alt: use strum dependency, macro to get at compile time the code,
    //but it is not really necessary here, as this is the only use case in the whole code
    //// level.as_ref() could be auto-generated by strum with #[strum(serialize_all = "lowercase")], return &'static str
    match level {
        //See pub struct LevelFilter(Option<Level>); of tracing, defining the OFF level to disable logs
        LogLevel::Off => "off",
        LogLevel::Error => "error",
        LogLevel::Warn => "warn",
        LogLevel::Info => "info",
        LogLevel::Debug => "debug",
        LogLevel::Trace => "trace",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_log_level() {
        assert_eq!(LogLevel::default(), LogLevel::Off);
    }
}
