name: miri.yml
on:
  push:
    branches: [ main ]
jobs:
  #To have the most secured snake in the world
  #Or just to test miri easily
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        #unmanaged starting a new process
        run: MIRIFLAGS=-Zmiri-disable-isolation cargo miri test -- --skip cli_integration_test
