name: miri.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
jobs:
  #To have the most secured snake in the world
  #Or just to test miri easily
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Miri toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: miri
          rustflags: ""
      - name: Setup Miri
        run: cargo miri setup
      - name: Test with Miri
        #unmanaged starting a new process
        #unmanaged sled unsafe call to libc::getrlimit
        #unmanaged access to log file
        run: MIRIFLAGS=-Zmiri-disable-isolation cargo miri test -- --skip game_logic::high_score --skip cli_integration_test --skip logging_tests
