name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Rust (version pinned via rust-toolchain.toml)
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Clippy (warnings allowed, otherwise add "-- -D warnings")
        run: cargo clippy --all-targets --all-features
      #1 thread otherwise delete files needs before tests end (safer for CI/CD)
      # NB: if tests are too long, consider cargo nextest (up to x3) but currently does
      #not manage doc tests: https://nexte.st/ (they have CI actions for installation)
      #Locally: cargo install cargo-binstall --locked && cargo binstall cargo-nextest --secure && cargo nextest run
      - name: Tests
        run: cargo test --verbose -- --test-threads=1

